---
- name: add 10gen repo key
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc state=present

- name: add 10gen repo
  copy: content='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen '
        dest=/etc/apt/sources.list.d/10gen.list
  register: repo

- name: update apt
  apt: update_cache=yes
  when_changed: $repo

- name: install mongodb-10gen
  apt: pkg=mongodb-10gen state=present

- copy: src=mongodb.conf dest=/etc/mongodb.conf
  notify: restart mongodb

- name: start mongodb
  service: name=mongodb state=started
  register: start_mongodb

- pause: seconds=30
  when_changed: $start_mongodb

- copy: src=initialise_replica_set.js dest=/tmp/initialise_replica_set.js
  tags:
    - replica_set

- name: initialise the replica set
  shell: cat /tmp/initialise_replica_set.js | mongo
  tags:
    - replica_set